version: '3.8'

services:
  latex-renderer:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount the app directory for development (comment out for production)
      - ./app:/app
    restart: unless-stopped
