version: '3.8'

services:
  latex-renderer-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount the app directory for development
      - ./app:/app
    restart: unless-stopped
